# Generated by Django 4.1.4 on 2023-05-14 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.CharField(blank=True, default='Hi ! I am using Dget media', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('profileimage', models.ImageField(default='profile.jpg', upload_to='profile_pics/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
